print("Welcome to tip calculator !!\n")
bill = float(input("What was the total bill "))
tip = int(input("What percentage tip would you like to give 10, 12 or 15 ? "))
people = int(input("How many people to split the bill ? "))
payable_amt = round((((bill * tip)/100)+ bill)/people, 2)
print(f"Each person should pay {payable_amt}")